# Generated by Django 3.2 on 2021-05-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='chead0',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='chead1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='chead2',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='contant0',
            field=models.CharField(default='', max_length=6000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='contant1',
            field=models.CharField(default='', max_length=6000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='contant2',
            field=models.CharField(default='', max_length=6000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head0',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head1',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tilte',
            field=models.CharField(max_length=60),
        ),
    ]
